### ISSUE TITLE
NSCalendarsUsageDescription - App rejected due to required permission and missing key

### ISSUE THREAD

**Issue by ojuniour** [jamesmontemagno/PermissionsPlugin#112]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 3.0.0.12
Device Tested On: iOS 11.4
Simulator Tested On: iOS 11.4
Version of VS:  15.7.2
Version of Xamarin:4.10.0.448
Versions of other things you are using:

### Steps to reproduce the Behavior
Using the permission plugin triggered a rejection from apple due to missing 'NSCalendarsUsageDescription' key that needs to acknowledge in the info.plist

### Expected Behavior
The plugin doesn't actually and shouldn't required calendar permission to function.

### Actual Behavior
Message from Apple when app is submitted for review:
"Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSCalendarsUsageDescription key with a string value explaining to the user how the app uses this data."

**Comment by jamesmontemagno** [comment]
see: https://github.com/jamesmontemagno/PermissionsPlugin#ios-specific

**Comment by jamesmontemagno** [comment]
This is addressed in 5.0-beta: https://montemagno.com/optimizing-xamarin-apps-libraries-with-the-linker/

**Comment by bobwhitten** [comment]
I'm a bit of newbie here...  using Xam.Plugin.Media to take pics in app (I was amazed -- AMAZED! -- at how easy this was).  But, when I submitted, I got App reject due to permission missing.     Having read the above coment about Plugin.Permission and 5.0 beta, I went to VS NuGet window and got Plugin.Permissions and bumped it (and only it) to v5,0.0-beta.  But, still getting rejects.  Did I miss something?  I have Linker Behavior set to "Link Framework SDKs Only" in Release.

**Comment by jamesmontemagno** [comment]
You would need to be on: https://www.nuget.org/packages/Xam.Plugin.Media/4.3.0-beta which uses the latest APIs. Then after that Link Framework SDKs ONly.

**Comment by pm64** [comment]
I'm facing a similar issue. Using the following builds with "Link Framework SDKs only":

- Xamarin.Forms v4.1.0.496342-pre2
- Plugin.Permissions v5.0.0-beta
- Xam.Plugin.Media v4.3.0-beta

Rejection reason: "The app's Info.plist file should contain a NSCalendarsUsageDescription key with a user-facing purpose string"

As with the OP, the app in question doesn't know/care about the calendar. Anything else that could account for this?

**Comment by pm64** [comment]
Should add that in addition to NSCalendarsUsageDescription, I'm also being inexplicably warned about NSLocationAlwaysUsageDescription and NSLocationWhenInUseUsageDescription. In these cases it is just a warning, not basis for rejection, but obviously still a concern.

**Comment by jamesmontemagno** [comment]
Are you using and calling Permissions Plugin anywhere yourself?

**Comment by pm64** [comment]
@jamesmontemagno - yes, I'm making the following 3 calls:

CheckPermissionStatusAsync(Permission.Storage)
RequestPermissionsAsync(new[] { Permission.Camera, Permission.Storage })
OpenAppSettings()

**Comment by jamesmontemagno** [comment]
Yes, if you use the old API like that then it will not get linked out. You must use the new api in 5.0

**Comment by MarcAlx** [comment]
To sum-up the solution to this problem (which was working for me).

1. Use `Plugin.Permissions v5.0.0-beta` (Forms and PCL)
2. If you don't have `Plugin.Permissions v5.0.0-beta` (or newer) but have `Xam.Plugin.Media` use `Xam.Plugin.Media v4.3.0-beta` (or newer) (Forms and PCL)
3. If you use directly the api to check permissions, be sure to not use a deprecated method (follow readme instructions, Visual Studio prompt you when you are using Deprecated methods).

**Comment by NatalGi** [comment]
I had the same issue, an I find out, that the Plugin.Geolocator (by James Montemagno) I am using refers to Plugin.Permissions, so unfortunately I need to add the NSCalendarsUsageDescription key
